#!/usr/bin/env bash

set -Eeuo pipefail
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
cd $script_dir

cd bin

./TestThermo01
./TestThermo02
./TestThermo03
./TestThermo04
./TestThermo05
./TestThermo06
./TestThermo07
./TestThermo08
./TestThermo09
./TestThermo10
./TestThermo11
./TestThermo12 > test12out.txt
tail -1 test12out.txt
./TestThermo13
./TestThermo14
./TestThermo30
./TestThermo31
./TestThermo32
./TestThermo33
./TestThermo40
./TestThermo41
./TestThermo42
./TestThermo43
./TestThermo44
./TestThermo45
./TestThermo46
./TestThermo47
./TestThermo48
./TestThermo49
./TestThermo50
./TestThermo51
./TestThermo52
./TestThermo53
./TestThermo54
./TestThermo55
./TestThermo56
./TestThermo57
./TestThermo58
./TestThermo59
./TestThermo60
