# This is a basic workflow to help you get started with Actions

name: ExtendedTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "extendedTests"
  extendedTests:

    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: copy data
        run: cp /home/max/proj/privateTesting/data/* data/

      - name: remove standard tests
        run: rm test/daily/*.F90

      - name: copy tests
        run: cp /home/max/proj/privateTesting/privateTests/*.F90 test/daily/

      - name: copy test driver
        run: cp /home/max/proj/privateTesting/run_private_tests .

      - name: make clean
        run: make veryclean

      - name: make
        run: make

      - name: make test
        run: make test

      - name: run tests
        run: bash ./run_private_tests > testresults.out

      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-test-results
          path: testresults.out

      - name: run fpdb carpet
        run: ./bin/carpet-FPDB

      - name: Upload FPDB success
        uses: actions/upload-artifact@v2
        with:
          name: output-FPDB-pass
          path: carpetFPDBPass.txt

      - name: Upload FPDB failures
        uses: actions/upload-artifact@v2
        with:
          name: output-FPDB-fail
          path: carpetFPDBFail.txt
